### ISSUE TITLE
cannot download indexes

### ISSUE THREAD

**Issue by lpantano** [jhhung/Tailor#2]
Hi,

that tool seems great! congrats!

I want to try it but I cannot download the indexes:

```
lftp -c "pget -n 4 http://www.jhhlab.tw/Tailor/index/hg18.tar.gz"
pget: Access failed: 403 Forbidden (/Tailor/index/hg18.tar.gz)
```

This would be better than creating the index since it needs more than 16GB of memory right?

thanks!

**Comment by jhhung** [comment]
Oops, our server hasn't yet changed the permission for the outsiders, will fix ASAP.
If your machine has limited memory, it might be a problem running Tailor as well, since Tailor uses 64-bit long integers to accommodate the address of reference longer than 4G, so just to store the index already takes much more space than other FM-index based tools, unfortunately... and thanks for your kind words, and hope you keep sending us your feedbacks after use.

**Comment by lpantano** [comment]
Thanks you! Do you know how much memory I will need for hg19?

will come back to you after I get this running. I have hope to get all 
these small RNA with additions with only one aligner.
